services:
  db:
    image: postgres:15-alpine
    container_name: daonfnc
    ports:
      - '12194:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: daonfnc
    volumes:
      - daonfnc_data:/var/lib/postgresql/data
    restart: always

volumes:
  daonfnc_data:
