services:
  db:
    image: postgres:15-alpine
    container_name: shabangnet-db
    ports:
      - '12194:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shabangnet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
